# Generated by Django 5.1.2 on 2025-10-06 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='company_images/')),
                ('drive_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IT', 'Information Technology'), ('FIN', 'Finance'), ('HC', 'Healthcare'), ('ED', 'Education'), ('MFC', 'Manufacturing')], max_length=50)),
            ],
        ),
    ]
