# Generated by Django 5.1.2 on 2025-10-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
